[env:lilygo_t3s3_rx]
platform = espressif32
board = esp32-s3-devkitc-1
board_upload.flash_size = 4MB
board_build.partitions = default.csv
framework = arduino
monitor_speed = 115200
lib_deps =
    jgromes/RadioLib@^6.6.0
    olikraus/U8g2@^2.35.0
    https://github.com/mrfaptastic/ESP32-HUB75-MatrixPanel-I2S-DMA.git
    adafruit/Adafruit GFX Library@^1.11.9
    adafruit/Adafruit BusIO@^1.16.1
build_flags =
    -DCORE_DEBUG_LEVEL=0
    -DARDUINO_USB_CDC_ON_BOOT=1
